name: Selenium Webdriver Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build the solution
      run: dotnet build --configuration Release --no-restore

    # Execute all unit tests in the solution
    - name: Execute tests
      run: dotnet test

    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/*.html'
    
    - name: Move Test Report to docs folder
      run: |
        mkdir -p docs
        cp UltimateQA/bin/Debug/net8.0/UltimateQATestReport.html docs/TestResults.html